//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Chat.Globalization.Errors {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Data.Chat.Globalization.Errors.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversation not found.
        /// </summary>
        public static string ConversationNotFound {
            get {
                return ResourceManager.GetString("ConversationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate user ids found.
        /// </summary>
        public static string DuplicateUserIds {
            get {
                return ResourceManager.GetString("DuplicateUserIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inválid user ids found.
        /// </summary>
        public static string InvalidUserIds {
            get {
                return ResourceManager.GetString("InvalidUserIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invited user not found.
        /// </summary>
        public static string InvitedUserNotFound {
            get {
                return ResourceManager.GetString("InvitedUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kicked user not found.
        /// </summary>
        public static string KickedUserNotFound {
            get {
                return ResourceManager.GetString("KickedUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message not found.
        /// </summary>
        public static string MessageNotFound {
            get {
                return ResourceManager.GetString("MessageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read message not found.
        /// </summary>
        public static string ReadMessageNotFound {
            get {
                return ResourceManager.GetString("ReadMessageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User conversation not found.
        /// </summary>
        public static string UserConversationNotFound {
            get {
                return ResourceManager.GetString("UserConversationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User conversation not found or is not active.
        /// </summary>
        public static string UserConversationNotFoundOrIsNotActive {
            get {
                return ResourceManager.GetString("UserConversationNotFoundOrIsNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User left the conversation.
        /// </summary>
        public static string UserLeftTheConversation {
            get {
                return ResourceManager.GetString("UserLeftTheConversation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User was kicked.
        /// </summary>
        public static string UserWasKicked {
            get {
                return ResourceManager.GetString("UserWasKicked", resourceCulture);
            }
        }
    }
}
